package kev.spring.mybatis.generator.entity;

import java.io.Serializable;

public class RcModAction implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_mod_actions.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_mod_actions.action_id
     *
     * @mbg.generated
     */
    private Integer actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_mod_actions.mod_id
     *
     * @mbg.generated
     */
    private Integer modId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_mod_actions.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rc_mod_actions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_mod_actions.id
     *
     * @return the value of rc_mod_actions.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_mod_actions.id
     *
     * @param id the value for rc_mod_actions.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_mod_actions.action_id
     *
     * @return the value of rc_mod_actions.action_id
     *
     * @mbg.generated
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_mod_actions.action_id
     *
     * @param actionId the value for rc_mod_actions.action_id
     *
     * @mbg.generated
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_mod_actions.mod_id
     *
     * @return the value of rc_mod_actions.mod_id
     *
     * @mbg.generated
     */
    public Integer getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_mod_actions.mod_id
     *
     * @param modId the value for rc_mod_actions.mod_id
     *
     * @mbg.generated
     */
    public void setModId(Integer modId) {
        this.modId = modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_mod_actions.is_deleted
     *
     * @return the value of rc_mod_actions.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_mod_actions.is_deleted
     *
     * @param isDeleted the value for rc_mod_actions.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_mod_actions
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RcModAction other = (RcModAction) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getActionId() == null ? other.getActionId() == null : this.getActionId().equals(other.getActionId()))
            && (this.getModId() == null ? other.getModId() == null : this.getModId().equals(other.getModId()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_mod_actions
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getActionId() == null) ? 0 : getActionId().hashCode());
        result = prime * result + ((getModId() == null) ? 0 : getModId().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_mod_actions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", actionId=").append(actionId);
        sb.append(", modId=").append(modId);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}