package kev.spring.mybatis.generator.entity;

import java.io.Serializable;
import java.util.Date;

public class UserModValue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.mod_id
     *
     * @mbg.generated
     */
    private Integer modId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.mod_name
     *
     * @mbg.generated
     */
    private String modName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.mod_value
     *
     * @mbg.generated
     */
    private Integer modValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.action_id
     *
     * @mbg.generated
     */
    private Integer actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.action_name
     *
     * @mbg.generated
     */
    private String actionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.sku_name
     *
     * @mbg.generated
     */
    private String skuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.policy_no
     *
     * @mbg.generated
     */
    private String policyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.evaluated_at
     *
     * @mbg.generated
     */
    private Date evaluatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mod_values.exported_num
     *
     * @mbg.generated
     */
    private Byte exportedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_mod_values
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.id
     *
     * @return the value of user_mod_values.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.id
     *
     * @param id the value for user_mod_values.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.mod_id
     *
     * @return the value of user_mod_values.mod_id
     *
     * @mbg.generated
     */
    public Integer getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.mod_id
     *
     * @param modId the value for user_mod_values.mod_id
     *
     * @mbg.generated
     */
    public void setModId(Integer modId) {
        this.modId = modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.mod_name
     *
     * @return the value of user_mod_values.mod_name
     *
     * @mbg.generated
     */
    public String getModName() {
        return modName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.mod_name
     *
     * @param modName the value for user_mod_values.mod_name
     *
     * @mbg.generated
     */
    public void setModName(String modName) {
        this.modName = modName == null ? null : modName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.mod_value
     *
     * @return the value of user_mod_values.mod_value
     *
     * @mbg.generated
     */
    public Integer getModValue() {
        return modValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.mod_value
     *
     * @param modValue the value for user_mod_values.mod_value
     *
     * @mbg.generated
     */
    public void setModValue(Integer modValue) {
        this.modValue = modValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.action_id
     *
     * @return the value of user_mod_values.action_id
     *
     * @mbg.generated
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.action_id
     *
     * @param actionId the value for user_mod_values.action_id
     *
     * @mbg.generated
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.action_name
     *
     * @return the value of user_mod_values.action_name
     *
     * @mbg.generated
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.action_name
     *
     * @param actionName the value for user_mod_values.action_name
     *
     * @mbg.generated
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.sku_name
     *
     * @return the value of user_mod_values.sku_name
     *
     * @mbg.generated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.sku_name
     *
     * @param skuName the value for user_mod_values.sku_name
     *
     * @mbg.generated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.company
     *
     * @return the value of user_mod_values.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.company
     *
     * @param company the value for user_mod_values.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.user_id
     *
     * @return the value of user_mod_values.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.user_id
     *
     * @param userId the value for user_mod_values.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.policy_no
     *
     * @return the value of user_mod_values.policy_no
     *
     * @mbg.generated
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.policy_no
     *
     * @param policyNo the value for user_mod_values.policy_no
     *
     * @mbg.generated
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo == null ? null : policyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.evaluated_at
     *
     * @return the value of user_mod_values.evaluated_at
     *
     * @mbg.generated
     */
    public Date getEvaluatedAt() {
        return evaluatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.evaluated_at
     *
     * @param evaluatedAt the value for user_mod_values.evaluated_at
     *
     * @mbg.generated
     */
    public void setEvaluatedAt(Date evaluatedAt) {
        this.evaluatedAt = evaluatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mod_values.exported_num
     *
     * @return the value of user_mod_values.exported_num
     *
     * @mbg.generated
     */
    public Byte getExportedNum() {
        return exportedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mod_values.exported_num
     *
     * @param exportedNum the value for user_mod_values.exported_num
     *
     * @mbg.generated
     */
    public void setExportedNum(Byte exportedNum) {
        this.exportedNum = exportedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mod_values
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserModValue other = (UserModValue) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getModId() == null ? other.getModId() == null : this.getModId().equals(other.getModId()))
            && (this.getModName() == null ? other.getModName() == null : this.getModName().equals(other.getModName()))
            && (this.getModValue() == null ? other.getModValue() == null : this.getModValue().equals(other.getModValue()))
            && (this.getActionId() == null ? other.getActionId() == null : this.getActionId().equals(other.getActionId()))
            && (this.getActionName() == null ? other.getActionName() == null : this.getActionName().equals(other.getActionName()))
            && (this.getSkuName() == null ? other.getSkuName() == null : this.getSkuName().equals(other.getSkuName()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPolicyNo() == null ? other.getPolicyNo() == null : this.getPolicyNo().equals(other.getPolicyNo()))
            && (this.getEvaluatedAt() == null ? other.getEvaluatedAt() == null : this.getEvaluatedAt().equals(other.getEvaluatedAt()))
            && (this.getExportedNum() == null ? other.getExportedNum() == null : this.getExportedNum().equals(other.getExportedNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mod_values
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getModId() == null) ? 0 : getModId().hashCode());
        result = prime * result + ((getModName() == null) ? 0 : getModName().hashCode());
        result = prime * result + ((getModValue() == null) ? 0 : getModValue().hashCode());
        result = prime * result + ((getActionId() == null) ? 0 : getActionId().hashCode());
        result = prime * result + ((getActionName() == null) ? 0 : getActionName().hashCode());
        result = prime * result + ((getSkuName() == null) ? 0 : getSkuName().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPolicyNo() == null) ? 0 : getPolicyNo().hashCode());
        result = prime * result + ((getEvaluatedAt() == null) ? 0 : getEvaluatedAt().hashCode());
        result = prime * result + ((getExportedNum() == null) ? 0 : getExportedNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mod_values
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", modId=").append(modId);
        sb.append(", modName=").append(modName);
        sb.append(", modValue=").append(modValue);
        sb.append(", actionId=").append(actionId);
        sb.append(", actionName=").append(actionName);
        sb.append(", skuName=").append(skuName);
        sb.append(", company=").append(company);
        sb.append(", userId=").append(userId);
        sb.append(", policyNo=").append(policyNo);
        sb.append(", evaluatedAt=").append(evaluatedAt);
        sb.append(", exportedNum=").append(exportedNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}