package kev.spring.mybatis.generator.dao;

import kev.spring.mybatis.generator.entity.UserAction;

public interface UserActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_actions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_actions
     *
     * @mbg.generated
     */
    int insert(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_actions
     *
     * @mbg.generated
     */
    int insertSelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_actions
     *
     * @mbg.generated
     */
    UserAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_actions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_actions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAction record);
}